//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelterDesctopApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalShelterDatabaseEntities : DbContext
    {
        public AnimalShelterDatabaseEntities()
            : base("name=AnimalShelterDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Dogs> Dogs { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
    }
}
