//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelterDesctopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int Id { get; set; }
        public int FoodRef { get; set; }
        public int VolunteerRef { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
